# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate cosine simialrity
#' @description Refer to https://gist.github.com/bobthecat/2903031
#' @param Xr a matrix
#' @export
cosine_similarity <- function(Xr) {
    .Call('_CIDER_cosine_similarity', PACKAGE = 'CIDER', Xr)
}

#' @export
rcpp_hello_world <- function() {
    .Call('_CIDER_rcpp_hello_world', PACKAGE = 'CIDER')
}

